[install]
is_configured = false
state = enabled

[ui]
is_visible = true
label = TA-flux Asset Classifier

[launcher]
author = Mikael Bjerkeland
description = Asset role classifier using firewall traffic ports and Splunk MLTK.
version = 0.1.0

[package]
id = TA-flux
check_for_updates = false
